sudo: enabled
dist: trusty

language: java
jdk:
  - oraclejdk9

branches:
  only:
    - master
    - 35-java-9-support

script:
  - ./gradlew clean report build

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - serhii.s.korol@gmail.com